# Generated by Django 5.0.6 on 2026-03-14 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['topic', 'difficulty'], name='quizzes_qui_topic_f44b20_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['creator', '-created_at'], name='quizzes_qui_creator_8b98ac_idx'),
        ),
    ]
