# Generated by Django 5.0.6 on 2026-03-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
        ('quizzes', '0003_quiz_available_from_quiz_available_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='quizzes', to='classrooms.classroom'),
        ),
    ]
